### PR TITLE
Added host configuration to MySQL config

### PR DESCRIPTION
**Pull request by moezzie**
Added the option to configure MySQL host and port.

### CODE REVIEW

**Comment by mingrammer** [comment]
Thank you.

Split the `Host` into `Host` and `Port` each would be better I think.

**Comment by mingrammer** [comment]
@moezzie Could you add `Port` field?

**Comment by moezzie** [comment]
Yeah, sounds good.
Maybe i was just a tiny bit lazy the first time around .

I've pushed another update separating the two.

**Comment by mingrammer** [comment]
Port should be int type

**Comment by mingrammer** [comment]
Thank you for contributing!

**Pull request merged**
